version: '3.9'

services:
    webstreamx:
        build: .
        container_name: webstreamx
        restart: unless-stopped
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=production
            - CONCURRENCY=1
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities: [gpu]
        volumes:
            - ./:/app
        runtime: nvidia
