version: '3.9'

services:
    webstreamx:
        build:
            dockerfile: .docker/Dockerfile
            context: ../
        container_name: webstreamx
        restart: unless-stopped
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=production
            - CONCURRENCY=1
            - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
            - NVIDIA_VISIBLE_DEVICES=all
            - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
